### ISSUE TITLE
Module Zero with EF Core

### ISSUE THREAD

**Issue by sohaibjaved44** [aspnetboilerplate/aspnet-core-template#14]
How about module zero with EF Core? are you going to release it in near future? as I can see if I select module zero I can't continue with EF Core?

**Comment by hikalkan** [comment]
This is because we could not find a good way of implementing [data filters](http://www.aspnetboilerplate.com/Pages/Documents/Data-Filters) with EF Core. It's required for soft delete and multitenancy.

**Comment by PMVDias** [comment]
I suppose that I some point they will make this possible in EF Core. Will you guys then upgrade to EF Core?
For an existent project with EF 4.6 will be easy to update to  EF Core?

**Comment by hikalkan** [comment]
Yes, eventually we want to move to .net core, EF Core and Identity Core.

**Comment by hikalkan** [comment]
This is already done.
