### ISSUE TITLE
CalculateContentRootFolder exception when updated to 1.1

### ISSUE THREAD

**Issue by gabrielrobert** [aspnetboilerplate/aspnet-core-template#17]
Hi,

I just upgraded my project to .NET Core (1.1, project.json -> .csproj) and had an issue with the current implementation of [CalculateContentRootFolder](https://github.com/aspnetboilerplate/aspnet-core-template/blob/master/src/AbpCompanyName.AbpProjectName.Core/Web/WebContentFolderHelper.cs) when unit testing.

I solved the problem replacing this:

`var coreAssemblyDirectoryPath = Path.GetDirectoryName(typeof(AbpProjectNameCoreModule).Assembly.Location);`

By this:

`var coreAssemblyDirectoryPath = Path.GetDirectoryName(AppContext.BaseDirectory);`

The original exception was `Could not find content root folder!` because the assembly was in AppData, where tests cannot find the bin path.

Are you aware of this issue? Of course, this happened using VS 2017.

**Comment by gabrielrobert** [comment]
Of course, this happened using VS 2017.

**Comment by hikalkan** [comment]
Oh, I was trying to understand for a few minuts. Haven't tried in VS 2017 yet.

**Comment by gabrielrobert** [comment]
@hikalkan Well, it's the only problem that occured during my migration. I'm csproj-ready as we speak now.

**Comment by hikalkan** [comment]
That's good :)

**Comment by ismcagdas** [comment]
Also solution offered here is applied https://github.com/aspnet/Hosting/issues/959#issuecomment-286351703
