### ISSUE TITLE
ASP.NET Core Boilerplate .NET Core

### ISSUE THREAD

**Issue by ar27111994** [aspnetboilerplate/aspnet-core-template#18]
Any chances of running this on .NET Core (Ubuntu)? Please Help!

**Comment by hikalkan** [comment]
not yet, since it works on .net framework 4.6.1.

**Comment by ar27111994** [comment]
Any tentative time-frame?

**Comment by hikalkan** [comment]
Not yet. Follow https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1485
