### ISSUE TITLE
The dependency  could not be resolved.

### ISSUE THREAD

**Issue by PMVDias** [aspnetboilerplate/aspnet-core-template#19]
Hi,

I can't run or build my project.
I'm getting the following errors resolving dependencies attached.
Any idea what could be the issue?
![error1](https://cloud.githubusercontent.com/assets/14943047/23063634/82dceac0-f503-11e6-9508-6b72b3bdd5a4.PNG)
![error2](https://cloud.githubusercontent.com/assets/14943047/23063639/87ed4fc8-f503-11e6-9b7a-3a80cc659497.PNG)

**Comment by hikalkan** [comment]
What is version in global.json. Also, what is the installed .net core versions in your computer? You can check C:\Program Files\dotnet\sdk folder for a list of sdk folders.

**Comment by PMVDias** [comment]
The .net core version installed is:DotNetCore.1.0.1-VS2015Tools.Preview2.0.3. The C:\Program Files\dotnet\sdk is 1.0.0-preview2-003131. About the  global.json don't see any version there!
![error3](https://cloud.githubusercontent.com/assets/14943047/23069099/0aec4e46-f51e-11e6-8cec-8570a1182a9e.PNG)

**Comment by hikalkan** [comment]
can you try to add

````
"version": "1.0.0-preview2-003131"
````

inside sdk

**Comment by PMVDias** [comment]
Same issue :/
![error4](https://cloud.githubusercontent.com/assets/14943047/23069334/e997f1d6-f51e-11e6-8987-a69e9067eedb.PNG)

**Comment by hikalkan** [comment]
These packages are available on nuget (and many developers using them). It should be sopmething related to your environment, but could not understand at first look.
Is that a fresh created project or are you upgrading packages? Have you close/open VS (believe, it works in many cases since nuget has some bugs).

**Comment by ismcagdas** [comment]
Can you close the solution and open agian after adding version to global.json ?

**Comment by PMVDias** [comment]
That worked! Thanks a lot for the help.
