### ISSUE TITLE
This aspnet-core-template can't run

### ISSUE THREAD

**Issue by hercules135** [aspnetboilerplate/aspnet-core-template#20]
![image](https://cloud.githubusercontent.com/assets/12913496/23829844/f1c73ee6-0736-11e7-9bab-f24a63d8ab16.png)

**I download the template from there but when it work only this in my browser:**

![image](https://cloud.githubusercontent.com/assets/12913496/23829871/805033ac-0737-11e7-9748-acc5a4992753.png)

**just the HTTP ERROR 500 and no more info or warning**

**I have try the Acme.SimpleTaskApp which can run in the same computer**

**Comment by hikalkan** [comment]
Have you created database using migrations? see doc: http://www.aspnetboilerplate.com/Pages/Documents/Zero/Startup-Template-Core

**Comment by prom3theu5** [comment]
He probably has the issue I have
The project is using xproj and not csproj like in vs2017, so After migration on first open, project.json is gone

I'm not sure how to do dotnet ef database update without it as it complains it's missing

**Comment by hikalkan** [comment]
Upgrade Migrator tool to the latest version, they solved the issue. see https://github.com/mrahhal/Migrator.EF6/issues/36

**Comment by hikalkan** [comment]
BTW, we have just released new template which uses the latest Migrator tool. You can download from http://www.aspnetboilerplate.com/Templates

**Comment by prom3theu5** [comment]
Cool - thanks :)
