### ISSUE TITLE
 Solution file error MSB5023:

### ISSUE THREAD

**Issue by ChiakiYu** [aspnetboilerplate/aspnet-core-template#23]
Solution file error MSB5023: Error parsing the nested project section in solution file. A project with the GUID "{A2213374-BB48-48FD-BBD4-81E6A961D866}" is listed as being nested under project "{AFAA0841-BD93-466F-B8F4-FB4EEC86F1FC}", but does not 
exist in the solution.

**Comment by ChiakiYu** [comment]
I download the template with ng2 in https://www.aspnetboilerplate.com/Templates

**Comment by hikalkan** [comment]
Thank you, we will fix this. But it is building in my VS2017.
