### ISSUE TITLE
CalculateRootFolder() not portable

### ISSUE THREAD

**Issue by SpiraMira** [aspnetboilerplate/aspnet-core-template#29]
Just a heads up. Hi ran into this while testing core+ng2 on macOS.
You use verbatim literal strings to construct the path to webHostFolder and webMvcFolder
Obviously won't work too well on nix systems like macOS and Linux ;-)

Try this instead for both:

````C#
var webHostFolder = Path.Combine(directoryInfo.FullName,string.Format("src{0}ZeroCoreAngularCore.Web.Host",Path.DirectorySeparatorChar));
````
Regards, P

**Comment by hikalkan** [comment]
Thanks a lot. Will fix this.
