### ISSUE TITLE
Adjust required to use "dotnet ef migrations add" 

### ISSUE THREAD

**Issue by diegoortizmatajira** [aspnetboilerplate/aspnet-core-template#31]
**NOTE**: Applies to DotNetCore template. I proved this on Windows and on Linux Ubuntu.

In order to be able to create migrations artifacts from dotnet CLI I had to manually add some lines to the 
{app}.EntityFrameworkCore.csproj

 ```
 <PropertyGroup>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
```
Source: [https://github.com/aspnet/EntityFramework/issues/7889](https://github.com/aspnet/EntityFramework/issues/7889)

after this I was able to execute an create the first Entity Framework Core migration.

Hope his helps to improve the solution template.

**Comment by hikalkan** [comment]
Thank you. We will add this.
