### ISSUE TITLE
Adjust related with {Path.DirectorySeparatorChar} on solution template 

### ISSUE THREAD

**Issue by diegoortizmatajira** [aspnetboilerplate/aspnet-core-template#32]
I'm testing the template for aspnetboilerplate for DotNet Core in Windows and Linux Ubuntu.

In order to get it running (Reading the connection string from web project) i had to change the WebContentFolderHelper.cs file in Core project.

The file was generated like 

`            return Path.Combine(directoryInfo.FullName, $"src\AbpCompanyName.AbpProjectName.Web");
`

but in order to run on linux had to change "\\" to "/"

`            return Path.Combine(directoryInfo.FullName, $"src/AbpCompanyName.AbpProjectName.Web");
`

After this change the app runs on Windows and Linux.

Hope this helps to improve the Solution template

**Comment by hikalkan** [comment]
Thank you.
We have fixed this (https://github.com/aspnetboilerplate/aspnet-core-template/commit/f2d1470b914d00e8b82123450ee8db6080ce7831) but not released yet.
duplicate: https://github.com/aspnetboilerplate/aspnet-core-template/issues/29
