### ISSUE TITLE
SQL Exception on running generated template

### ISSUE THREAD

**Issue by kanvuduc** [aspnetboilerplate/aspnet-core-template#36]
> An exception has been raised that is likely due to a transient failure. If you are connecting to a SQL Azure database consider using SqlAzureExecutionStrategy.

I could connect to my local SQL Server with SQL Server Management Studio or within Visual Studio.

**Comment by hikalkan** [comment]
You can consider to use SqlAzureExecutionStrategy. Also switch to DbContextEfTransactionStrategy (https://www.aspnetboilerplate.com/Pages/Documents/EntityFramework-Integration#transaction-management) which is better for Azure.

**Comment by kanvuduc** [comment]
I managed to run the template. Thank you, @hikalkan. The issue is that I need to create the database before I could run the code. is that required?

**Comment by hikalkan** [comment]
It's probably needed on Azure. Your connection string's security may not has priviledge to create database or Azure may not support creating db via SQL commands. Actually I don't know the reason, you can search web if you want to know more.

**Comment by kanvuduc** [comment]
No. It's on my local machine. Neither trusted connection nor admin user could work.

**Comment by hikalkan** [comment]
OK. The exception message make me thought that it's related to Azure.
For your local SQL server, it should create the database. We or our customers haven't this issue before. Exception message says it's a transient error. Have you tried again?

**Comment by kanvuduc** [comment]
What do you mean transient error? I just did the workaround by create the db first.

**Comment by hikalkan** [comment]
Exception mssage says: "An exception has been raised that is likely due to a transient failure."
That means if you try again it may work :)

**Comment by hikalkan** [comment]
BTW this is SQL Server's or Entity Framework's exception. Also, running the migration is done by EF. There is nothing related to AspNet Zero here.

**Comment by kanvuduc** [comment]
:). Yep, mightbe.
