### ISSUE TITLE
Is there any special depedency on ASP.NET Core MVC 1.1.2?

### ISSUE THREAD

**Issue by kanvuduc** [aspnetboilerplate/aspnet-core-template#38]
I tried to deploy the generated template onto Azure, but it doesn't support .NETCore 1.1.2 yet.

Does this template depend on any special features of ASP.NET Core MVC 1.1.2 and its related stuff?

I would like to downgrade to .NETCore 1.1.

**Comment by hikalkan** [comment]
No, it doesn't use any special feature for .net core 1.1.2.

**Comment by kanvuduc** [comment]
It's now runnable on Azure.
