### ISSUE TITLE
NU1603 Issue on ASP.Net Core 2.X Template v3.41

### ISSUE THREAD

**Issue by reuwarwema** [aspnetboilerplate/aspnet-core-template#46]
After a fresh download and lauching the project, i get

`Warning	NU1603	Abp.AspNetCore.SignalR 3.3.0-preview1 depends on Microsoft.AspNetCore.SignalR (>= 1.0.0-preview1-27891) but Microsoft.AspNetCore.SignalR 1.0.0-preview1-27891 was not found. An approximate best match of Microsoft.AspNetCore.SignalR 1.0.0-preview2-24707 was resolved.	academicprof.Web.Core	D:\AcademicProfessionals\academicprof\aspnet-core\src\academicprof.Web.Core\academicprof.Web.Core.csproj	1`	

and 

`Warning	NU1603	Microsoft.Extensions.Primitives 2.0.0-preview2-24707 depends on System.Runtime.CompilerServices.Unsafe (>= 4.4.0-preview2-25225-02) but System.Runtime.CompilerServices.Unsafe 4.4.0-preview2-25225-02 was not found. An approximate best match of System.Runtime.CompilerServices.Unsafe 4.4.0-preview2-25405-01 was resolved.	academicprof.Web.Core	D:\AcademicProfessionals\academicprof\aspnet-core\src\academicprof.Web.Core\academicprof.Web.Core.csproj	1`

**Comment by acjh** [comment]
> `Microsoft.AspNetCore.SignalR 1.0.0-preview1-27891 was not found.`

See aspnetboilerplate/aspnetboilerplate#2831.

> `System.Runtime.CompilerServices.Unsafe 4.4.0-preview2-25225-02 was not found.`

Install the stable version [`4.4.0`](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/4.4.0) of the package.
