### ISSUE TITLE
Unexpected IRepository behaviour

### ISSUE THREAD

**Issue by ArturKarbone** [aspnetboilerplate/aspnet-core-template#5]
Hi

 I tweaked aspnet-core-template a bit by adding Insert method

![](https://i.imgur.com/iOCxTTz.png)

However for some reasons it does not save an entity. List methods work just fine for me.

Here is a gist of my ProductAppService class https://gist.github.com/ArturKarbone/9c97b8ddfc6b58f379c4ddd78f395187

My expectation was that proxy implementation of IRepository<WhateverEntity> also implements Inserts

Thanks

**Comment by ArturKarbone** [comment]
Looks like it worked out eventually. But behaviour is very strange stiil. Here is a client code and sql profiler screenshot. It's obvious that i expect to see insert statement in the profiler first and then select statement. But it works vice verca, in addition to that i figured out **that insert statement is being triggered only after Controller.Index returned.** 

![](https://i.imgur.com/gPZEPab.png)

Is it bug or somehow related to UnitOfWork? If so can if force Insert repository method to execute immediatelly?

**Comment by hikalkan** [comment]
Yes, it's related to unit of work. changes are saved after your method (Insert action) is completed. If you want to immediately insert, use ``CurrentUnitOfWork.SaveChanges`` or ``_repository.InsertAndGetId(...)`` method.

**Comment by hikalkan** [comment]
While this is not an issue yet, there is a very strange case in EF Core. It sets Id to a negative value (-2147482647 in may case) when we add an entity to DbContext. And it remains like that until we call savechanges.
I will investigate that and ask to EF team.

**Comment by hikalkan** [comment]
Created an issue for EF: https://github.com/aspnet/EntityFramework/issues/6147

**Comment by hikalkan** [comment]
I'm closing this issue since all these are expected..
