### ISSUE TITLE
The term 'Update-Database' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by CS-beglnner** [aspnetboilerplate/aspnet-core-template#55]
I just downloaded .Net Core template, I'm following documents and restoring packages with `dotnet restore` then I build my solution but when setting web.host as startup project then selecting myApp.EFCore as default project in pmc; Update-Database commend resolve this error 

```
The term 'update-database' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.At line:1 char:1
 update-database

     CategoryInfo          : ObjectNotFound: (update-database:String) [], CommandNotFoundException
    FullyQualifiedErrorId : CommandNotFoundException
```

VS 2017 ver 15.5.6 
.Net Core 2
Any help is tankful

**Comment by ismcagdas** [comment]
Try restarting visual studio.

**Comment by CS-beglnner** [comment]
@ismcagdas I restarting windows and vs and upgrading PowerShell but some error

**Comment by ismcagdas** [comment]
@CS-beglnner I couldn't figure it out. Can you run "Update-Database" in any other project ? You can try an empty ASP.NET Core project for example.

**Comment by CS-beglnner** [comment]
@ismcagdas I try that before you asking and all ef cmd done! I have this problem just with Abp Core projects(Abp .net framework and empaty core project works well). I found some issue in Visual Studio 15.5.x forums and they says use the project without 'src/'. I think that's not solution

**Comment by ismcagdas** [comment]
@CS-beglnner can you share the link you have found ? It might be helpful.

**Comment by CS-beglnner** [comment]
@ismcagdas Dependencies is not restoring and package manager not found any package. 

> can you share the link you have found ? It might be helpful.

Yes Sir, give me a second for searching my browser history

**Comment by CS-beglnner** [comment]
@ismcagdas Check this please, [#6324](https://github.com/NuGet/Home/issues/6324)
I moved **src** directory from version folder to myApp root and renamed **asp-core** to AspCore and everything done! Its a Nuget bug in VS 15.5.x [Visual Studio forum](https://developercommunity.visualstudio.com/content/problem/160750/nuget-bug-in-vs155.html)

**Comment by CS-beglnner** [comment]
For similar issue: You can using "_" _underline_ for dash and points in folder names if you don't like change original directory mapping.

**Comment by ismcagdas** [comment]
Thanks a lot for the feedback. I think it will be helpful for many developers.
