### ISSUE TITLE
it is error in  test modelSkipDbContextRegistration=false

### ISSUE THREAD

**Issue by onlystar007** [aspnetboilerplate/aspnet-core-template#68]

**Comment by onlystar007** [comment]
`if (!SkipDbContextRegistration)
            {
                Configuration.Modules.AbpEfCore().AddDbContext<FRMSCoreDbContext>(options =>
                {
                    if (options.ExistingConnection != null)
                    {
                        FRMSCoreDbContextConfigurer.Configure(options.DbContextOptions, options.ExistingConnection);
                    }
                    else
                    {
                        FRMSCoreDbContextConfigurer.Configure(options.DbContextOptions, options.ConnectionString);
                    }
                });
            }`

when I set  SkipDbContextRegistration=false,  the "options.ConnectionString" is not right;   
"options.ConnectionString= Default"

**Comment by ismcagdas** [comment]
Why do you need to set SkipDbContextRegistration to false ?
