### ISSUE TITLE
Angular 2 template

### ISSUE THREAD

**Issue by stasoQ** [aspnetboilerplate/aspnet-core-template#7]
Hello. Thank you very much for the work done.

Will you support Angular / Angular 2 out of the box in the future ?

**Comment by hikalkan** [comment]
Yes, We will create a Angular2 based startup template.

**Comment by stasoQ** [comment]
Thank for the answer.

**Comment by badre429** [comment]
any timeline for creating angular 2 template

**Comment by hikalkan** [comment]
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1485#issuecomment-280425494

**Comment by ismcagdas** [comment]
Currently there is Angular 7 template on https://github.com/aspnetboilerplate/module-zero-core-template and we will upgrade it to v8 soon.
