### ISSUE TITLE
Angular & TypeScript Services with ASPNETCore

### ISSUE THREAD

**Issue by iyhammad** [aspnetboilerplate/aspnet-core-template#8]
Hi,
I'm trying to explore AspNetCore Template. The Problem is, I can't generate the angular services from the application service and also the typescript. only the JQuery generator is working.

Am I missing something?

Thanks,

**Comment by hikalkan** [comment]
Hi,

We did not start to work with Angular template yet. Current AspNet Core template supports MVC.
With the development of AspNet Core integration, we changed script creation, unified and generalized it. We will add direct Typescript support and Angular2 template soon.

**Comment by iyhammad** [comment]
I will close this issue. We can now use nswag.
